DROP TABLE TUNING_EVENT;

CREATE TABLE TUNING_EVENT (
ID BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR2(64) NOT NULL,
COUNTRY VARCHAR2(64) NOT NULL,
CITY VARCHAR2(64) NOT NULL,
POSTER BLOB DEFAULT NULL,
LATITUDE FLOAT NOT NULL,
LONGITUDE FLOAT NOT NULL,
DESCRIPTION VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY (ID));

# Spring security tables
CREATE TABLE USERS (
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	ENABLED	SMALLINT NOT NULL,
	PRIMARY KEY (USERNAME) );
	
CREATE TABLE AUTHORITIES (
	USERNAME VARCHAR(50) NOT NULL, 
	AUTHORITY VARCHAR(50) NOT NULL, 
	FOREIGN KEY (USERNAME) REFERENCES USERS);